@startuml
!include <archimate/Archimate>
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!include DEVICONS/java.puml
!include DEVICONS/mysql.puml
!include DEVICONS/react.puml
!include DEVICONS/html5.puml

!define SPRITESURL https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/v1.1/sprites
!include SPRITESURL/auth0-icon.puml
!include SPRITESURL/twilio-icon.puml
!include SPRITESURL/cloudinary-icon.puml
!include SPRITESURL/stripe.puml
!include SPRITESURL/google-gmail.puml

SetDefaultLegendEntries("")

AddElementTag("java", $shape=EightSidedShape(), $bgColor="Green", $fontColor="white", $legendText="Java File \neight sided")
AddElementTag("ext_service", $shape=EightSidedShape(), $bgColor="Gray", $fontColor="white" ,$legendText="External Services\neight sided")
AddElementTag("typescript", $shape=RoundedBoxShape(), $bgColor="DodgerBlue", $fontColor="white", $legendText="TSX File")
AddElementTag("html", $shape=RoundedBoxShape(), $bgColor="OrangeRed", $fontColor="white", $legendText="HTML Files")
AddElementTag("npm_libraries", $shape=EightSidedShape(), $bgColor="Red", $fontColor="white" ,$legendText="NPM Libraries\neight sided")
AddElementTag("TSX_component", $shape=EightSidedShape(), $bgColor="Blue", $fontColor="white" ,$legendText="TSX Component\neight sided")

Container_Ext(auth, "Auth0", "Auth SaaS", "Auth0 is an easy to implement, adaptable authentication and authorization platform.", $sprite="auth0-icon", $tags="ext_service")
Container_Ext(email, "Gmail SMTP", "SMTP Service", "The google SMTP emailing system.", $sprite="google-gmail", $tags="ext_service")
Container_Ext(cloud, "Cloudinary", "Cloud Service", "Cloud storage service that stores media and pdf reports.", $sprite="cloudinary-icon", $tags="ext_service")
Container_Ext(stripe, "Stripe", "Payment Service", "Payment processing service for handling transactions between advertisings and medias owners.", $sprite="stripe-icon", $tags="ext_service")
Container_Ext(twilio, "Twilio", "SMS Service", "Reminding Media Owners to provide proof of displaying ads on their media.", $sprite="twilio-icon", $tags="ext_service")

        rectangle "API" as API #line.dashed{

                Container(securityFilter, "Security Filter", "Component: Spring Security Filter", "Filters all the requests to the API.", $sprite="java", $tags="java")

                package "Media"{
                    Container(MediaController, "Media Controller", "Component: Spring Boot Rest Controller", "Allows Media Owners to manage MediaAssets, Admins to manage both MediaAssets and MediaTypes, and Advertisers to view MediaAssets.", $sprite="java", $tags="java")
                    Container(MediaService, "Media Service", "Component: Spring Boot Service", "Provides the functionalities to get, update, create and delete.", $sprite="java", $tags="java")
                    Container(MediaRepo, "Media Repository", "Component: JPA Repository", "Makes requests to the database to fetch or update data.", $sprite="java", $tags="java")

                    MediaController -[dashed,#LimeGreen]-> MediaService  : **Uses**
                    MediaService -[dashed,#LimeGreen]-> MediaRepo  : **Uses**
                }

                package "Advertising" {
                    Container(advertisingController, "advertising Controller", "Component: Spring Boot Rest Controller", "Allows Advertisers and Admins to manage Advertisements and Advertisement Campaigns.", $sprite="java", $tags="java")
                    Container(advertisingService, "advertising Service", "Component: Spring Boot Service", "Provides the functionalities to get, update, create and delete.", $sprite="java", $tags="java")
                    Container(advertisingRepo, "advertising Repository", "Component: JPA Repository", "Makes requests to the database to fetch or update data.", $sprite="java", $tags="java")

                    advertisingController -[dashed,#LimeGreen]-> advertisingService  : **Uses**
                    advertisingService -[dashed,#LimeGreen]-> advertisingRepo  : **Uses**
                }

                package "Transaction" {
                    Container(transactionController, "Transaction Controller", "Component: Spring Boot Rest Controller", "Allows Media Owners and Advertisers to view Invoices and Transactions, and Admins to manage them.", $sprite="java", $tags="java")
                    Container(transactionService, "Transaction Service", "Component: Spring Boot Service", "Provides the functionalities to get, update, create and delete.", $sprite="java", $tags="java")
                    Container(transactionRepo, "Transaction Repository", "Component: JPA Repository", "Makes requests to the database to fetch or update data.", $sprite="java", $tags="java")

                    transactionController -[dashed,#LimeGreen]-> transactionService  : **Uses**
                    transactionService -[dashed,#LimeGreen]-> transactionRepo  : **Uses**
                }

                package "Moderation"{
                    Container(moderationController, "Moderation Controller", "Component: Spring Boot Rest Controller", "Allows Media Owners and Advertisers to create Reports, and Admins to manage them.", $sprite="java", $tags="java")
                    Container(moderationService, "Moderation Service", "Component: Spring Boot Service", "Provides the functionalities to get, update, create and delete.", $sprite="java", $tags="java")
                    Container(moderationRepo, "Moderation Repository", "Component: JPA Repository", "Makes requests to the database to fetch or update data.", $sprite="java", $tags="java")

                    moderationController -[dashed,#LimeGreen]-> moderationService  : **Uses**
                    moderationService -[dashed,#LimeGreen]-> moderationRepo  : **Uses**
                }

                package "Analytics"{
                    Container(reportController, "Report Controller", "Component: Spring Boot Rest Controller", "Allows all users to view and generate Reports.", $sprite="java", $tags="java")
                    Container(reportService, "Report Service", "Component: Spring Boot Service", "Provides the functionalities to get, update, create and delete.", $sprite="java", $tags="java")
                    Container(reportRepo, "Report Repository", "Component: JPA Repository", "Makes requests to the database to fetch or update data.", $sprite="java", $tags="java")

                    reportController -[dashed,#LimeGreen]-> reportService  : **Uses**
                    reportService -[dashed,#LimeGreen]-> reportRepo  : **Uses**
                }

                package "Email"{
                    Container(mailerService,"Mailer Service", "Component: Spring Boot Service", "Sends emails to the users.", $sprite="java", $tags="java")
                }

                package "Auth"{
                    Container(authService,"Auth Service", "Component: Spring Boot Service", "Authenticate the users", $sprite="java", $tags="java")
                }

                package "Payment"{
                    Container(paymentService,"Payment Service", "Component: Spring Boot Service", "Handles payment for the users.", $sprite="java", $tags="java")
                }

                package "SMS"{
                    Container(smsService,"SMS Service", "Component: Spring Boot Service", "Sends sms to the users.", $sprite="java", $tags="java")
                }

                package "File"{
                    Container(fileService,"File Service", "Component: Spring Boot Service", "Handles files for the users.", $sprite="java", $tags="java")
                }

                moderationService -[dashed]-> mailerService  : **Sends Email using**
                reportService -[dashed]-> mailerService  : **Sends Email using**

                fileService -[dashed]-> cloud  : **Send Email Using**\n[SMTP/TCP/IP]
                smsService -[dashed]-> twilio  : **Send Email Using**\n[SMTP/TCP/IP]
                mailerService -[dashed]-> email  : **Send Email Using**\n[SMTP/TCP/IP]
                paymentService -[dashed]-> stripe  : **Send Email Using**\n[SMTP/TCP/IP]

                advertisingService -[dashed]-> fileService  : **Get Files using**
                MediaService -[dashed]-> fileService  : **Send Files using**
                MediaService -[dashed]-> smsService  : **Send SMS using**

                transactionService  -[dashed]-> paymentService  : **Send Payment using**

                securityFilter -[dashed,#RoyalBlue]-> advertisingController  : **Direct Request**
                securityFilter -[dashed,#RoyalBlue]-> moderationController  : **Direct Request**
                securityFilter -[dashed,#RoyalBlue]-> reportController  : **Direct Request**
                securityFilter -[dashed,#RoyalBlue]-> MediaController  : **Direct Request**
                securityFilter -[dashed,#RoyalBlue]-> transactionController  : **Direct Request**
                securityFilter -[dashed,#RoyalBlue]-> "authService"  : **Direct Request**

                "authService" -[dashed,#Crimson]-> "auth"  : **Uses**\n[OAuth2/OpenID]
            SHOW_LEGEND()
        }

        ContainerDb(db, "Database", "Database: MySQL", "Stores all the data for the system.", $sprite="mysql", $tags="database")

        moderationRepo -[dashed,#LimeGreen]-> db  : **SQL/TCP**\n[JBDC]

        advertisingRepo -[dashed,#LimeGreen]-> db  : **SQL/TCP**\n[JBDC]

        reportRepo -[dashed,#LimeGreen]-> db  : **SQL/TCP**\n[JBDC]

        MediaRepo -[dashed,#LimeGreen]-> db  : **SQL/TCP**\n[JBDC]

AddElementTag("webSite", $shape=RoundedBoxShape(), $bgColor="DodgerBlue", $fontColor="white", $legendText="Single-Page Application")
AddElementTag("webApp", $shape=RoundedBoxShape(), $bgColor="OrangeRed", $fontColor="white", $legendText="Web Application")

Container(application, "Web Application", "HTML", "Delivers the static content for the Single Page Application.", $sprite="html5", $tags="webApp")
Container(webPage, "Single-Page Application", "REACT JS", "Provides a GUI interface that contains all the functionalities of the Spring boot application. Uses REACT Router to handle the multiple pages.", $sprite="react",$tags="webSite")

application -[dashed]> webPage  : **Renders**

webPage -[dashed]-> securityFilter  : **Makes API calls**\n[HTTPS/JSON]

@enduml