@startuml
!theme plain
hide circle
top to bottom direction
!pragma useVerticalIf on
skinparam dpi 350
skinparam packageStyle rectangle
skinparam rectangle {
  BackgroundColor #f7f4eb
  BorderColor Black
}

' === DDD DEFINITIONS ===
!define ENTITY(e) class e <<Entity>>
!define AGGREGATE(a) class a <<Aggregate>>
!define AGGREGATE_ROOT(ar) class ar <<Aggregate Root>>
!define VALUE_OBJECT(vo) class vo <<Value Object>>
!define ENUM(enum) class enum <<Enum>>

title Envision Ad Platform - Domain Driven Design Domain Model

' ===============================
' Media
' ===============================
package "Media Subdomain" #LightGreen {
  AGGREGATE_ROOT(MediaAsset) #LightBlue {
    title: String
    estimatedWeeklyViews: Int
    pricePerWeek: Decimal
    width: Float
    height: Float
    image: URL
    mediaCorners: double[4]
  }

  ENTITY(MediaType) #LightBlue {
    name: String
    description: String
  }

  VALUE_OBJECT(MediaTypeIdentifier) #Bisque {
    mediaTypeId: UUID
  }

  ENUM(Status) #Orange {
    ACTIVE
    INACTIVE
    PENDING
    REJECTED
  }

  VALUE_OBJECT(MediaIdentifier) #Bisque {
    mediaId: UUID
  }

  VALUE_OBJECT(MediaLocation) #Bisque {
    latitude: Float
    longitude: Float
    address: String
  }

  MediaType "1" o--> "1" MediaTypeIdentifier
  MediaAsset "1" o--> "1..*" MediaLocation
  MediaAsset "1" o--> "1" MediaIdentifier
  MediaAsset "1" o--> "1" MediaTypeIdentifier
  MediaAsset "1" o--> "1" Status
}

' ===============================
' Advertiser
' ===============================
package "Advertising Subdomain" #LightCoral {
  AGGREGATE(AdvertisementCampaign) #LightBlue {
    startDate: Date
    endDate: Date
    budget: Decimal
  }

  AGGREGATE(Advertisement) #LightBlue {
    mediaId: UUID
    screenTimeMinutes: Int
    cost: Decimal
    approvedByOwner: Boolean
  }

  ENUM(Status) #Orange {
    ACTIVE
    PENDING
    REJECTED
    EXPIRED
  }

  VALUE_OBJECT(AdIdentifier) #Bisque {
    adId: UUID
  }

  VALUE_OBJECT(AdCampaignIdentifier) #Bisque {
    adCampaignId: UUID
  }

  AdvertisementCampaign "1" o--> "1" AdCampaignIdentifier
  AdvertisementCampaign "1" o--> "1..*" AdIdentifier
  AdvertisementCampaign "1" o--> "1" Status
  Advertisement "1" o--> "1" AdIdentifier
}

' ===============================
' TRANSACTIONS
' ===============================
package "Transactions Subdomain" #LightPink {
  AGGREGATE_ROOT(Transaction) #LightBlue {
    companyName: String
    amount: Decimal
    timestamp: DateTime
  }

  ENTITY(Invoice) #LightBlue {
    dueDate: Date
    paid: Boolean
  }

   ENUM(Status) #Orange {
     SUCCESS
     PENDING
     FAILED
   }

  VALUE_OBJECT(TransactionIdentifier) #Bisque {
    transactionId: UUID
  }

  VALUE_OBJECT(InvoiceIdentifier) #Bisque {
    invoiceId: UUID
  }

  VALUE_OBJECT(BillingAddress) #Bisque {
    street : String
    city : String
    province : String
    postalCode : String
  }

  Transaction "1" o--> "1" BillingAddress
  Transaction "1" o--> "1" InvoiceIdentifier
  Transaction "1" o--> "1" TransactionIdentifier
  Transaction "1" o--> "1" Status
  Invoice "1" o--> "1" InvoiceIdentifier
}

' ===============================
' MODERATION
' ===============================
package "Moderation Subdomain" #LightCyan {
  ENTITY(VerificationRequest) #LightBlue {
    userId: UUID
    submittedDocs: URL
  }

  AGGREGATE(UserReport) #LightBlue {
    userId: UUID
    reason: String
    description: String
    proof: URL
  }

  ENTITY(ContentModeration) #LightBlue {
    mediaId: UUID
    reason: String
  }

  ENUM(Status) #Orange {
    PENDING
    APPROVED
    REJECTED
  }

   VALUE_OBJECT(ContentModerationIdentifier) #Bisque {
     contentModerationId: UUID
   }

   VALUE_OBJECT(UserReportIdentifier) #Bisque {
     userReportId: UUID
   }

   VALUE_OBJECT(VerificationRequestIdentifier) #Bisque {
     verificationRequestId: UUID
   }

  VerificationRequest "1" o--> "1" VerificationRequestIdentifier
  VerificationRequest "1" o--> "1" Status
  ContentModeration "1" o--> "1" ContentModerationIdentifier
  ContentModeration "1" o--> "1" Status
  UserReport "1" o--> "1" UserReportIdentifier
  UserReport "1" o--> "1" Status
}

' ===============================
' ANALYTICS
' ===============================
package "ANALYTICS Subdomain" #LightGray {
  AGGREGATE_ROOT(Report) #LightBlue {
    userId: UUID
    generatedAt: DateTime
  }

  AGGREGATE(ReportData) #LightBlue {
    value: String
    name: String
    description: String
  }

  VALUE_OBJECT(ReportIdentifier) #Bisque {
    reportID: UUID
  }

  VALUE_OBJECT(ReportDataIdentifier) #Bisque {
    reportDataId: UUID
  }

  Report "1" o--> "1" ReportIdentifier
  Report "1" o--> "1..*" ReportDataIdentifier
  ReportData "1" o--> "1" ReportDataIdentifier
}

@enduml
