@startuml
left to right direction

' --- Increase spacing and make the box larger test ---
skinparam ranksep 40
skinparam nodesep 30
skinparam rectangle {
  Padding 40
  Margin 40
}

actor Advertiser as ADV
actor "Media Owner" as MO


rectangle "Publish Ad" {
' --- Advertiser use cases ---
  usecase "Preview Ad on Media" as Preview
  usecase "Submit Ad for Approval" as Submit
  usecase "Confirm Proof of Display" as ConfirmProof
  usecase "Make Ad Payment" as Pay
  usecase "Upload Ad Content" as UploadContent
  usecase "Select Ad Start/End Dates" as SelectDates

  ' --- Media Owner use cases ---
  usecase "Approve/Deny Ad" as ApproveAd
  usecase "Download Ad Content" as DownloadContent
  usecase "Provide Proof of Display" as ProvideProof
  usecase "Retrieve Ad for Display" as DisplayAd

  ' --- Actor connections ---
  ADV -- Submit
  ADV -- ConfirmProof

  DisplayAd -- MO
  ProvideProof  -- MO

  ' --- Relationships  ---
  Submit <.. Preview : <<extends>>
  Submit ..> SelectDates : <<includes>>
  Submit ..> UploadContent : <<includes>>
  Submit ..> Pay : <<includes>>
  ConfirmProof ..> ProvideProof  : <<includes>>
  DownloadContent <.. DisplayAd : <<includes>>
  ApproveAd <.. DisplayAd : <<includes>>

}
@enduml